### ISSUE TITLE
Throwing a 404 error

### ISSUE THREAD

**Issue by cowboysdude** [tshort/MMM-KitchenTimer#1]
I believe there are naming issues here so it cannot find the files and throws a 404 error.

I forked it .. check out my fork.  :)

**Comment by tshort** [comment]
You're right. To make my version work, you can't do a straight clone. You have to clone into a directory called "kitchen-timers". Do you mind making a pull request from your fork?

**Comment by cowboysdude** [comment]
No not at all.  :)  Great job on it!  It will be prefect on my 'command center' mirror... it's touch.

There you go pull request in ...  Thank you.
